### ISSUE TITLE
I can't see the sims on TS4 simripper and I can't convert it on DAE format

### ISSUE THREAD

**Issue by VDuran89** [CmarNYC-Tools/TS4SimRipper#3]
Hi, when I try to run the app on Mac with Parallels, I can't get a preview of any sim I select. Sometimes the screen shows "Working..." but never loads the sim. Then when message "Working..." has dissapered, the sim never loads, put it shows the list of outfits. I thought it is a problem just with images, and I try to click on DAE button. When I do it, a pop-up appers and has this message:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at TS4SimRipper.GEOM..ctor(GEOM sourceMesh) in C:\Users\A\Desktop\CmarNYC_TS4SimRipperSource\GEOM.cs:line 874
   at TS4SimRipper.DAE..ctor(GEOM[] geomArray, String[] meshNames, RIG rig, Boolean Y_Up, Boolean clean, String& errorMsg) in C:\Users\A\Desktop\CmarNYC_TS4SimRipperSource\ColladaDAE.cs:line 563
   at TS4SimRipper.Form1.SaveModelMorph(MeshFormat format) in C:\Users\A\Desktop\CmarNYC_TS4SimRipperSource\PreviewControl.cs:line 1622
   at TS4SimRipper.Form1.SaveDAE_button_Click(Object sender, EventArgs e) in C:\Users\A\Desktop\CmarNYC_TS4SimRipperSource\Form1.cs:line 1474
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Private.CoreLib.dll
----------------------------------------
TS4SimRipper
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:////Mac/Home/Documents/CmarNYC_TS4SimRipper_3_14_2_3/TS4SimRipper.dll
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Runtime.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.WindowsDesktop.App/6.0.27/System.Drawing.Common.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2724.7001
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.WindowsDesktop.App/6.0.27/System.Windows.Forms.dll
----------------------------------------
System.Text.Encoding.CodePages
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Text.Encoding.CodePages.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2724.7001
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.WindowsDesktop.App/6.0.27/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Collections.Specialized.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Collections.dll
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/Microsoft.Win32.Registry.dll
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Threading.dll
----------------------------------------
s4pi.Package
    Assembly Version: 2002.10.2050.28502
    Win32 Version: 2002.10.2050.28502
    CodeBase: file:////Mac/Home/Documents/CmarNYC_TS4SimRipper_3_14_2_3/s4pi.Package.dll
----------------------------------------
s4pi.Interfaces
    Assembly Version: 2104.21.1514.18445
    Win32 Version: 2104.21.1514.18445
    CodeBase: file:////Mac/Home/Documents/CmarNYC_TS4SimRipper_3_14_2_3/s4pi.Interfaces.dll
----------------------------------------
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/mscorlib.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.WindowsDesktop.App/6.0.27/System.Configuration.ConfigurationManager.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.ObjectModel.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Core.dll
----------------------------------------
System.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Linq.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.dll
----------------------------------------
s4pi.Settings
    Assembly Version: 2104.21.1515.18463
    Win32 Version: 2104.21.1515.18463
    CodeBase: file:////Mac/Home/Documents/CmarNYC_TS4SimRipper_3_14_2_3/s4pi.Settings.dll
----------------------------------------
PresentationCore
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2724.7003
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.WindowsDesktop.App/6.0.27/PresentationCore.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.2724.7001
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.WindowsDesktop.App/6.0.27/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.ComponentModel.TypeConverter.dll
----------------------------------------
WindowsFormsIntegration
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2724.7003
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.WindowsDesktop.App/6.0.27/WindowsFormsIntegration.dll
----------------------------------------
PresentationFramework
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2724.7003
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.WindowsDesktop.App/6.0.27/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2724.7003
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.WindowsDesktop.App/6.0.27/WindowsBase.dll
----------------------------------------
System.Xaml
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2724.7003
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.WindowsDesktop.App/6.0.27/System.Xaml.dll
----------------------------------------
DirectWriteForwarder
    Assembly Version: 6.0.2.0
    Win32 Version: 6,0,2724,7003 @Commit: 12a1b47c5b9b55841e0aa39bb36c15ac05d4ce8a
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.WindowsDesktop.App/6.0.27/DirectWriteForwarder.dll
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Runtime.Extensions.dll
----------------------------------------
System.Runtime.CompilerServices.VisualC
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Runtime.CompilerServices.VisualC.dll
----------------------------------------
System.Diagnostics.Debug
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Diagnostics.Debug.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Collections.NonGeneric.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Numerics.Vectors.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.WindowsDesktop.App/6.0.27/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Collections.Concurrent.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.ComponentModel.dll
----------------------------------------
System.Memory
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Memory.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Runtime.Loader.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Private.Uri.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Private.Xml.dll
----------------------------------------
System.Net.WebClient
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Net.WebClient.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Text.Encoding.Extensions.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2724.7003
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.WindowsDesktop.App/6.0.27/UIAutomationTypes.dll
----------------------------------------
System.IO.Packaging
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.WindowsDesktop.App/6.0.27/System.IO.Packaging.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Net.Primitives.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Threading.ThreadPool.dll
----------------------------------------
System.Windows.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.WindowsDesktop.App/6.0.27/System.Windows.Extensions.dll
----------------------------------------
UIAutomationProvider
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2724.7003
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.WindowsDesktop.App/6.0.27/UIAutomationProvider.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Diagnostics.Process.dll
----------------------------------------
PresentationFramework.Aero2
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2724.7003
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.WindowsDesktop.App/6.0.27/PresentationFramework.Aero2.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.WindowsDesktop.App/6.0.27/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2724.7001
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.WindowsDesktop.App/6.0.27/System.Drawing.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Text.RegularExpressions.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Xml.XmlSerializer
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Xml.XmlSerializer.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Diagnostics.Tracing.dll
----------------------------------------
PresentationFramework-SystemXml
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2724.7003
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.WindowsDesktop.App/6.0.27/PresentationFramework-SystemXml.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
protobuf-net.Core
    Assembly Version: 3.0.0.0
    Win32 Version: 3.2.30.709
    CodeBase: file:////Mac/Home/Documents/CmarNYC_TS4SimRipper_3_14_2_3/protobuf-net.Core.dll
----------------------------------------
protobuf-net
    Assembly Version: 3.0.0.0
    Win32 Version: 3.2.30.709
    CodeBase: file:////Mac/Home/Documents/CmarNYC_TS4SimRipper_3_14_2_3/protobuf-net.dll
----------------------------------------
System.Reflection.Emit
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Reflection.Emit.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Reflection.Primitives.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Private.CoreLib.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:////Mac/Home/Documents/CmarNYC_TS4SimRipper_3_14_2_3/System.Collections.Immutable.dll
----------------------------------------
DDSPanel
    Assembly Version: 2002.10.2050.28504
    Win32 Version: 2002.10.2050.28504
    CodeBase: file:////Mac/Home/Documents/CmarNYC_TS4SimRipper_3_14_2_3/DDSPanel.dll
----------------------------------------
s4pi.ImageResource
    Assembly Version: 2104.21.1513.18410
    Win32 Version: 2104.21.1513.18410
    CodeBase: file:////Mac/Home/Documents/CmarNYC_TS4SimRipper_3_14_2_3/s4pi.ImageResource.dll
----------------------------------------
System.Net.Requests
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Net.Requests.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Reflection.Metadata.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.IO.Compression.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2724.6912
    CodeBase: file:///C:/Program%20Files/dotnet/x64/shared/Microsoft.NETCore.App/6.0.27/System.Diagnostics.FileVersionInfo.dll
----------------------------------------

************** JIT Debugging **************

**Comment by andrews4s** [comment]
Hi @VDuran89,
I'm running this in vmware fusion on a mac and it is working. What do you have set for your TS4 game installation folder in the setup?

**Comment by zethesimmer** [comment]
> Hi @VDuran89, I'm running this in vmware fusion on a mac (game files installed on the mac side) and it is working. What do you have set for your TS4 game installation folder in the setup?

Hey, Do you think you could help me? I am having the same issue.
